---
- name: Check if Homebrew is already installed
  command: which brew
  register: brew_installed
  ignore_errors: true

- name: Install Homebrew if not installed
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_installed.failed
  environment:
    NONINTERACTIVE: "1"  # To avoid user interaction during install

- name: Install Brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - gh
    - tree
    - terraform
    - kubernetes-cli
    - git
    - gh
    - zsh-autosuggestions
    - awscli

- name: Install Brew cask packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  install_options: cask
  loop:
    - visual-studio-code
    - google-chrome
